### ISSUE TITLE
Hardware buttons double tap default action

### ISSUE THREAD

**Issue by Cypher01** [ResurrectionRemix-Devices/device_oneplus_oneplus3#2]
I use a OnePlus 3 running RR-O-v6.0.0-20180220-oneplus3-Official.zip.

The default action for double tapping the back button should be nothing, I also configured it manually to nothing. But it anyway goes home when double tapping it, which is annoying when I just want to go back two times.

The default action for double tapping the recent apps button should be nothing, I again also configured it manually to nothing. But it anyway opens the last app when double tapping it.

Please fix this and really do nothing, when it's configured to nothing.

The home button seams not to be affected, it really does nothing when configured to do nothing.

Also the long press behaviour seems to work for all three buttons, it really does nothing when configured to do nothing.

**Comment by varund7726** [comment]
Don't post issues in github

**Comment by varund7726** [comment]
This issue is already being looked into since past 2 weeks .its not easy to find the cause so please avoiding demanding

**Comment by varund7726** [comment]
Also the recent apps thing is an aosp feature .we can't do anything about it

**Comment by Cypher01** [comment]
Of course we can do something about it. AOSP stands for Android Open Source Project. It doesn't make sense to be able to remap the double tap to other actions than the AOSP standard (which works), but not to nothing.

**Comment by varund7726** [comment]
So you do something about it then if your so confident .and BTW back button issue has just been fixed .

**Comment by varund7726** [comment]
Even If you tap regents button after a gap of 4 seconds or more its still gonna take you to the last app . so this isn't a double tap issue . get your facts straight kid

**Comment by Cypher01** [comment]
Wow, come down buddy. You couldn't know, but I'm also a developer. And telling me, a bug in an open source software cannot be fixed is simply bullshit. And other roms, also based on AOSP, don't have this problem, so even if I weren't a developer, logical thought tells me, that it's bullshit when you say this cannot be fixed.

Nevertheless, let's stop this discussion here. I appreciate your work and look forward to an even better and bugfixed Resurrection Remix! :-)

**Comment by varund7726** [comment]
Dude, you may be a developer , but your don’t seem to be having any experience in ROM development
again you need to get a couple of facts straight
1. The Recents double tap "Bug" you are referring to is not a bug but its more of a feature.
2. This feature is not even using the double tap API since even after tapping the button twice with a gap of even 1 minute in  bewteen, it switches back to last app.
If you keep your action as last app through DUI action utils , you will notice that the app switch is a lot faster. This is NOT the case in this scenario. Its a stock aosp behaviour and this is how google wants it to be and so do other users so i WILL NOT change that.
Yes other roms may have this FEATURE removed but I dont want to remove it .GO test a nexus/pixel running stock 8.1 and you’ll see

The reason why i lost it is because when a user of our rom comes and reports stuff. thats fine totally ok, butyou did not provide me a single logcat. If you read our RR readme we have mentioned multiple tiimes , do not open issues on github , but looks like you didn’t read the readme. Again , completely fine. BUT beind a fellow developer , you didnt provide me a single log and used the word "annoying" which i hate in such situations .

**Comment by Cypher01** [comment]
OK, it's a different story, when you say you don't want to change this behaviour. But then at least the Settings app must not offer the possibility to set double tap to nothing.

A logcat ... for this ... you must be joking.

Sorry, "annoying" was never meant to attack you. I just wanted to write a useful constructive bug report.

As I said, let's stop this discussion here. If you want to have the last word, feel free, I'm out. Thank you!

**Comment by varund7726** [comment]
Kiddo , a logcat provides all info .even in this situation which is how I fixed the back button issue . You still have a whole lot to learn . My suggestion , don't try to act smart and pass suggestions to people more experienced .
